"""empty message

Revision ID: 2e23425a07e5
Revises: 35c4307c44b1
Create Date: 2022-02-08 00:43:24.706591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e23425a07e5'
down_revision = '35c4307c44b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
