"""empty message

Revision ID: 6dc61e737960
Revises: ec1a3ccccf88
Create Date: 2022-02-08 14:04:18.123274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc61e737960'
down_revision = 'ec1a3ccccf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
