"""empty message

Revision ID: a40704af0d7f
Revises: f6831c162b8d
Create Date: 2022-02-08 16:53:29.942359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40704af0d7f'
down_revision = 'f6831c162b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
